export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_ADD_IMAGE = "AUTH_ADD_IMAGE";
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

export const GET_LISTINGS_BY_FILTERS = "GET_LISTINGS_BY_FILTERS";
export const GET_LISTINGS_BY_FILTERS_SUCCESS =
  "GET_LISTINGS_BY_FILTERS_SUCCESS";
export const GET_LISTINGS_BY_FILTERS_FAIL = "GET_LISTINGS_BY_FILTERS_FAIL";

export const GET_LISTINGS_BY_USERID = "GET_LISTINGS_BY_USERID";
export const GET_LISTINGS_BY_USERID_SUCCESS = "GET_LISTINGS_BY_USERID_SUCCESS";
export const GET_LISTINGS_BY_USERID_FAIL = "GET_LISTINGS_BY_USERID_FAIL";
export const GET_LISTINGS_BY_ADDRESS = "GET_LISTINGS_BY_ADDRESS";
export const GET_LISTINGS_BY_ADDRESS_START = "GET_LISTINGS_BY_ADDRESS_START";
export const GET_LISTINGS_BY_ADDRESS_SUCESS = "GET_LISTINGS_BY_ADDRESS_SUCESS";
export const GET_LISTINGS_BY_ADDRESS_FAIL = "GET_LISTINGS_BY_ADDRESS_FAIL";
